# Generated by Django 3.0.5 on 2020-04-09 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_offer',
        ),
    ]
