# Generated by Django 3.0.5 on 2020-04-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'В обоботке'), (2, 'В пути'), (3, 'Доставлено')], default=1),
        ),
    ]
